{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3b31f71f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q1. What is the purpose of the try statement?\n",
    "\n",
    "\"\"\"Lets take do a real world example of the try-except block.\n",
    "\n",
    "   The program asks for numeric user input. Instead the user types characters in the input box. The program normally \n",
    "   would crash. But with a try-except block it can be handled properly.\n",
    "\n",
    "   The try except statement prevents the program from crashing and properly deals with it.\n",
    "   \n",
    "   try:\n",
    "    x = input(\"Enter number: \")\n",
    "    x = x + 1\n",
    "    print(x)\n",
    "except:\n",
    "    print(\"Invalid input\")\n",
    "\n",
    "Entering invalid input, makes the program continue normally:\n",
    "\n",
    "  The try except statement can be extended with the finally keyword, this will be executed if no exception is thrown:\n",
    "\n",
    "finally:\n",
    "    print(\"Valid input.\")\n",
    "\n",
    "  The program continues execution if no exception has been thrown.\n",
    "\n",
    "  There are different kinds of exceptions: ZeroDivisionError, NameError, TypeError and so on. Sometimes modules define \n",
    "  their own exceptions.\n",
    "\n",
    "  The try-except block works for function calls too:\n",
    "  \n",
    "  def fail():\n",
    "    1 / 0\n",
    "\n",
    "try:\n",
    "    fail()\n",
    "except:\n",
    "    print('Exception occured')\n",
    "\n",
    "print('Program continues')\n",
    "\n",
    "This outputs:\n",
    "\n",
    " $ python3 example.py\n",
    "\n",
    "Exception occured\n",
    "Program continues\n",
    "\n",
    "If you are a beginner, then I highly recommend this book.\n",
    "try finally\n",
    "\n",
    "A try-except block can have the finally clause (optionally). The finally clause is always executed.\n",
    "So the general idea is:\n",
    "\n",
    "try:\n",
    "    <do something>\n",
    "except Exception:\n",
    "    <handle the error>\n",
    "finally:\n",
    "    <cleanup>\n",
    "\n",
    "For instance: if you open a file you’ll want to close it, you can do so in the finally clause.\n",
    "\n",
    "try: \n",
    "    f = open(\"test.txt\")\n",
    "except: \n",
    "    print('Could not open file')\n",
    "finally:\n",
    "    f.close()\n",
    "\n",
    "print('Program continue')\n",
    "\n",
    "try else\n",
    "\n",
    "  The else clause is executed if and only if no exception is raised. This is different from the finally clause that’s \n",
    "  always executed.\n",
    "\n",
    "try:\n",
    "    x = 1\n",
    "except:\n",
    "    print('Failed to set x')\n",
    "else:\n",
    "    print('No exception occured')\n",
    "finally:\n",
    "    print('We always do this')\n",
    "    \n",
    "  Output:\n",
    "\n",
    " No exception occured\n",
    " We always do this\n",
    "\n",
    "You can catch many types of exceptions this way, where the else clause is executed only if no exception happens.\n",
    "\n",
    "try:\n",
    "    lunch()\n",
    "except SyntaxError:\n",
    "    print('Fix your syntax')\n",
    "except TypeError:\n",
    "    print('Oh no! A TypeError has occured')\n",
    "except ValueError:\n",
    "    print('A ValueError occured!')\n",
    "except ZeroDivisionError:\n",
    "    print('Did by zero?')\n",
    "else:\n",
    "    print('No exception')\n",
    "finally:\n",
    "    print('Ok then')\"\"\"\n",
    "\n",
    "#Q2. What are the two most popular try statement variations?\n",
    "\n",
    "\"\"\"Try-except:-\n",
    "\n",
    "  Lets take do a real world example of the try-except block.\n",
    "\n",
    "  The program asks for numeric user input. Instead the user types characters in the input box. The program normally \n",
    "  would crash. But with a try-except block it can be handled properly.\n",
    "\n",
    "  The try except statement prevents the program from crashing and properly deals with it.\n",
    "  \n",
    "  try:\n",
    "    x = input(\"Enter number: \")\n",
    "    x = x + 1\n",
    "    print(x)\n",
    "except:\n",
    "    print(\"Invalid input\")\n",
    "\n",
    "Entering invalid input, makes the program continue normally:\n",
    "\n",
    " The try except statement can be extended with the finally keyword, this will be executed if no exception is thrown:\n",
    "\n",
    "finally:\n",
    "    print(\"Valid input.\")\n",
    "\n",
    "  The program continues execution if no exception has been thrown.\n",
    "\n",
    "  There are different kinds of exceptions: ZeroDivisionError, NameError, TypeError and so on. Sometimes modules define \n",
    "  their own exceptions.\n",
    "\n",
    "  The try-except block works for function calls too:\n",
    "  \n",
    "  def fail():\n",
    "    1 / 0\n",
    "\n",
    "try:\n",
    "    fail()\n",
    "except:\n",
    "    print('Exception occured')\n",
    "\n",
    "print('Program continues')\n",
    "\n",
    "This outputs:\n",
    "\n",
    " $ python3 example.py\n",
    "\n",
    "Exception occured\n",
    "Program continues\n",
    "\n",
    "  Try finally:-\n",
    "\n",
    "A try-except block can have the finally clause (optionally). The finally clause is always executed.\n",
    "So the general idea is:\n",
    "\n",
    "try:\n",
    "    <do something>\n",
    "except Exception:\n",
    "    <handle the error>\n",
    "finally:\n",
    "    <cleanup>\n",
    "    \n",
    "    For instance: if you open a file you’ll want to close it, you can do so in the finally clause.\n",
    "\n",
    "try: \n",
    "    f = open(\"test.txt\")\n",
    "except: \n",
    "    print('Could not open file')\n",
    "finally:\n",
    "    f.close()\n",
    "\n",
    "print('Program continue')\"\"\"\n",
    "\n",
    "#Q3. What is the purpose of the raise statement?\n",
    "\n",
    "\"\"\"Only an exception handler (or a function that a handler calls, directly or indirectly) can use raise without any \n",
    "   expressions. A plain raise statement reraises the same exception object that the handler received. The handler terminates, \n",
    "   and the exception propagation mechanism keeps searching for other applicable handlers. Using a raise without expressions \n",
    "   is useful when a handler discovers that it is unable to handle an exception it receives, so the exception should keep\n",
    "   propagating.\n",
    "   \n",
    "   When only expression1 is present, it can be an instance object or a class object. In this case, if expression1 is an \n",
    "   instance object, Python raises that instance. When expression1 is a class object, raise instantiates the class without \n",
    "   arguments and raises the resulting instance. When both expressions are present, expression1 must be a class object. raise \n",
    "   instantiates the class, with expression2 as the argument (or multiple arguments if expression2 is a tuple), and raises the \n",
    "   resulting instance.\n",
    "   \n",
    "   Here’s an example of a typical use of the raise statement:\n",
    "\n",
    "def crossProduct(seq1, seq2):\n",
    "    if not seq1 or not seq2:\n",
    "        raise ValueError, \"Sequence arguments must be non-empty\"\n",
    "    return [ (x1, x2) for x1 in seq1 for x2 in seq2 ]\n",
    "    \n",
    "    The crossProduct function returns a list of all pairs with one item from each of its sequence arguments, but first \n",
    "    it tests ...\"\"\"\n",
    "\n",
    "#Q4. What does the assert statement do, and what other statement is it like?\n",
    "\n",
    "\"\"\"Python has built-in assert statement to use assertion condition in the program. assert statement has a condition \n",
    "   or expression which is supposed to be always true. If the condition is false assert halts the program and gives an \n",
    "   AssertionError.\n",
    "   \n",
    "  Syntax for using Assert in Pyhton:\n",
    "\n",
    "  assert <condition>\n",
    "\n",
    "  assert <condition>,<error message>\n",
    "  \n",
    "  In Python we can use assert statement in two ways as mentioned above.\n",
    "\n",
    "    1. assert statement has a condition and if the condition is not satisfied the program will stop and give AssertionError.\n",
    "    2. assert statement can also have a condition and a optional error message. If the condition is not satisfied assert \n",
    "       stops the program and gives AssertionError along with the error message.\n",
    "       \n",
    "   Let's take an example, where we have a function that will calculate the average of the values passed by the user and the \n",
    "   value should not be an empty list. We will use assert statement to check the parameter and if the length is of the passed \n",
    "   list is zero, the program halts.\n",
    "   \n",
    "   Example 1: Using assert without Error Message\n",
    "\n",
    "def avg(marks):\n",
    "    assert len(marks) != 0\n",
    "    return sum(marks)/len(marks)\n",
    "\n",
    "mark1 = []\n",
    "print(\"Average of mark1:\",avg(mark1))\n",
    "\n",
    "  When we run the above program, the output will be:\n",
    "\n",
    "AssertionError\n",
    "\n",
    "  We got an error as we passed an empty list mark1 to assert statement, the condition became false and assert stops the \n",
    "  program and give AssertionError.\n",
    "\n",
    "  Now let's pass another list which will satisfy the assert condition and see what will be our output.\n",
    "  \n",
    "  Example 2: Using assert with error message\n",
    "\n",
    "def avg(marks):\n",
    "    assert len(marks) != 0,\"List is empty.\"\n",
    "    return sum(marks)/len(marks)\n",
    "\n",
    "mark2 = [55,88,78,90,79]\n",
    "print(\"Average of mark2:\",avg(mark2))\n",
    "\n",
    "mark1 = []\n",
    "print(\"Average of mark1:\",avg(mark1))\n",
    "\n",
    "  When we run the above program, the output will be:\n",
    "\n",
    "Average of mark2: 78.0\n",
    "AssertionError: List is empty.\n",
    "\n",
    "  We passed a non-empty list mark2 and also an empty list mark1 to the avg() function and we got output for mark2 list but \n",
    "  after that we got an error AssertionError: List is empty. The assert condition was satisfied by the mark2 list and program \n",
    "  to continue to run.\"\"\"\n",
    "\n",
    "#Q5. What is the purpose of the with/as argument, and what other statement is it like?\n",
    "\n",
    "\"\"\"The with statement in Python is used for resource management and exception handling. You’d most likely find it when \n",
    "   working with file streams. For example, the statement ensures that the file stream process doesn’t block other processes \n",
    "   if an exception is raised, but terminates properly.\n",
    "\n",
    "  The code block below shows the try-finally approach to file stream resource management.\n",
    "  \n",
    "  file = open('file-path', 'w') \n",
    "try: \n",
    "    file.write('Lorem ipsum') \n",
    "finally: \n",
    "    file.close() \n",
    "\n",
    "Normally, you’d want to use this method for writing to a file, but the with statement offers a cleaner approach:\n",
    "\n",
    "with open('file-path', 'w') as file: \n",
    "    file.write('Lorem ipsum') \n",
    "    \n",
    "  The with statement simplifies our write process to just two lines.\n",
    "\n",
    "It is also used in database CRUD processes. This example was taken from this site:\n",
    "\n",
    "def get_all_songs():\n",
    "    with sqlite3.connect('db/songs.db') as connection:\n",
    "        cursor = connection.cursor()\n",
    "        cursor.execute(\"SELECT * FROM songs ORDER BY id desc\")\n",
    "        all_songs = cursor.fetchall()\n",
    "        return all_songs\n",
    "\n",
    "Here, with is used to query an SQLite database and return its content.\"\"\""
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
